version: '3'
services:

    server:
        build:
          dockerfile: Dockerfile
          context: ./Server
        ports:
          - '5000:5000'
        environment:
            - IPADDRESS=172.30.138.120

    client1:
        build: 
          dockerfile: Dockerfile
          context: ./Client 
        ports: 
          - '5003:5003'
        environment:
            - FLASKPORT=5003
            - STOCKFISHPORT=8082
            - IPADDRESS=172.30.138.120

    stockfish1:
        build: 
          dockerfile: Dockerfile
          context: ./Stockfish
        ports: 
          - '8082:8082'
        environment:
            - STOCKFISHPORT=8082        

    # Add as many client with the different port
    client2:
        build: 
          dockerfile: Dockerfile
          context: ./Client 
        ports: 
          - '5004:5004'
        environment:
            - FLASKPORT=5004
            - STOCKFISHPORT=8083
            - IPADDRESS=172.30.138.120


    stockfish2:
        build: 
          dockerfile: Dockerfile
          context: ./Stockfish
        ports: 
          - '8083:8083'
        environment:
            - STOCKFISHPORT=8083  
