version: '3'
services:

    server:
        build:
          dockerfile: Dockerfile
          context: ./Server
        ports:
          - '5000:5000'

    client1:
        build: 
          dockerfile: Dockerfile
          context: ./Client 
        ports: 
          - '5001:5001'
        environment:
            - FLASKPORT=5001
            - STOCKFISHPORT=8080

    stockfish1:
        build: 
          dockerfile: Dockerfile
          context: ./Stockfish
        ports: 
          - '8080:8080'
        environment:
            - STOCKFISHPORT=8080        

    # Add as many client with the different port
    client2:
        build: 
          dockerfile: Dockerfile
          context: ./Client 
        ports: 
          - '5002:5002'
        environment:
            - FLASKPORT=5002
            - STOCKFISHPORT=8081


    stockfish2:
        build: 
          dockerfile: Dockerfile
          context: ./Stockfish
        ports: 
          - '8081:8081'
        environment:
            - STOCKFISHPORT=8081  
