apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server-container
          image: completedcode_server
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
          - name: IPADDRESS
            value: "127.0.0.1"


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: server-api
#   labels:
#     app: server-api
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 5000
#     protocol: TCP
#     targetPort: 5000
#   selector:
#     app: server-api


# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: server-ingress
#   annotations:
# spec:
#   rules:
#   - host: server.world
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: server-api
#             port:
#               number: 5000
