# our base image
FROM python:3.9-slim
 
# install Python modules needed by the Python app
COPY ../../requirements.txt .

RUN pip install -r requirements.txt

RUN mkdir -p "/Completed Code/Client"

#copy everything into the image
ADD ["../../Completed Code/Client", "Completed Code/Client"]

# tell the port number the container should expose
EXPOSE 5001

# run the application
CMD ["python", "-u", "Completed Code/Client/Client.py", "5001", "8080"]

